In [1]:
import numpy as np

In [2]:
un_array = np.array( [7, 77, 777 ,1235] )
un_array

array([   7,   77,  777, 1235])

In [3]:
type( un_array )

numpy.ndarray

In [4]:
type( un_array.shape )

tuple

In [5]:
un_array.shape

(4,)

In [6]:
un_array = np.array( [ [7, 77, 777 ,1235], [7, 77, 777 ,1235] ])
un_array

array([[   7,   77,  777, 1235],
       [   7,   77,  777, 1235]])

In [7]:
type( un_array.shape )

tuple

In [8]:
un_array.shape

(2, 4)

In [9]:
un_array = np.array( [ [17, 277, 777 ,1235], [7, 77, 777 ,1235],  [7, 77, 777 ,1235],  [7, 77, 777 ,1235] ])
un_array

array([[  17,  277,  777, 1235],
       [   7,   77,  777, 1235],
       [   7,   77,  777, 1235],
       [   7,   77,  777, 1235]])

In [10]:
un_array.shape

(4, 4)

In [11]:
un_array[2,2]

np.int64(777)

In [12]:
ej1 = np.zeros( (1080, 1920, 3) )
ej1

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
ej2 = np.full( (2,2), 9.1 )
ej2

array([[9.1, 9.1],
       [9.1, 9.1]])

In [14]:
ej3 = np.eye( 7,7 )
ej3

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [15]:
ej4 = np.ones( (10,7,2) )
ej4

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1

In [16]:
ej5 = np.random.random( (5,5) )
ej5

array([[0.97928707, 0.28929469, 0.38203136, 0.10502747, 0.64249277],
       [0.78538794, 0.05684562, 0.70820229, 0.23243308, 0.07643277],
       [0.29819736, 0.82682002, 0.83906003, 0.50094397, 0.38756237],
       [0.87643961, 0.96139094, 0.6784821 , 0.92561779, 0.24372857],
       [0.71691832, 0.04842505, 0.77987151, 0.07296911, 0.60552151]])

In [17]:
indices = np.array( [ [11, 12, 13, 14], [21, 22, 23, 24],  [31, 32, 33, 34],  [41, 42, 43, 44] ])
indices

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [18]:
cols = np.array( [0, 1, 2, 0])
rows = np.arange(4)

In [19]:
cols

array([0, 1, 2, 0])

In [20]:
rows

array([0, 1, 2, 3])

In [21]:
for row, col in zip(rows, cols ):
    print( row, col )
    print(indices[row, col])

0 0
11
1 1
22
2 2
33
3 0
41
