In [3]:
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Input
from tensorflow.keras import Model

In [99]:
doc = 'Me gusta el Deep Learning'
doc = doc.lower()
doc = doc.split()
values = np.array(doc)
values


array(['me', 'gusta', 'el', 'deep', 'learning'], dtype='<U8')

In [100]:
label_encoder = LabelEncoder()
label_encoder

LabelEncoder()

In [101]:
integer_encoder = label_encoder.fit_transform(values)
integer_encoder

array([4, 2, 1, 0, 3])

In [102]:
onehot_encoder = OneHotEncoder(sparse_output=False)
onehot_encoder

OneHotEncoder(sparse_output=False)

In [103]:
integer_encoder = integer_encoder.reshape( len(integer_encoder), 1 )
integer_encoder

array([[4],
       [2],
       [1],
       [0],
       [3]])

In [104]:
onehot_encoder = onehot_encoder.fit_transform(integer_encoder  )
onehot_encoder

array([[0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [105]:
text = open("C:/Users/jesus/Desktop/curso IA/Libro-Deep-Learning-introduccion-practica-con-Keras-1a-parte.txt", "rb").read().decode(encoding='utf-8')
len(text)

201709

In [106]:
vocab = sorted(set(text))
vocab

['\n',
 ' ',
 '!',
 '"',
 '#',
 '%',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 '[',
 ']',
 '_',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '\xad',
 'ÿ',
 'Š',
 '‡',
 '…']

In [107]:
char2idx = { u:i for i,u in enumerate(vocab) }
char2idx

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '#': 4,
 '%': 5,
 "'": 6,
 '(': 7,
 ')': 8,
 '*': 9,
 '+': 10,
 ',': 11,
 '-': 12,
 '.': 13,
 '/': 14,
 '0': 15,
 '1': 16,
 '2': 17,
 '3': 18,
 '4': 19,
 '5': 20,
 '6': 21,
 '7': 22,
 '8': 23,
 '9': 24,
 ':': 25,
 ';': 26,
 '<': 27,
 '=': 28,
 '>': 29,
 '?': 30,
 '@': 31,
 'A': 32,
 'B': 33,
 'C': 34,
 'D': 35,
 'E': 36,
 'F': 37,
 'G': 38,
 'H': 39,
 'I': 40,
 'J': 41,
 'K': 42,
 'L': 43,
 'M': 44,
 'N': 45,
 'O': 46,
 'P': 47,
 'Q': 48,
 'R': 49,
 'S': 50,
 'T': 51,
 'U': 52,
 'V': 53,
 'W': 54,
 'X': 55,
 'Y': 56,
 '[': 57,
 ']': 58,
 '_': 59,
 'a': 60,
 'b': 61,
 'c': 62,
 'd': 63,
 'e': 64,
 'f': 65,
 'g': 66,
 'h': 67,
 'i': 68,
 'j': 69,
 'k': 70,
 'l': 71,
 'm': 72,
 'n': 73,
 'o': 74,
 'p': 75,
 'q': 76,
 'r': 77,
 's': 78,
 't': 79,
 'u': 80,
 'v': 81,
 'w': 82,
 'x': 83,
 'y': 84,
 'z': 85,
 '\xad': 86,
 'ÿ': 87,
 'Š': 88,
 '‡': 89,
 '…': 90}

In [152]:
idx2char = np.array(vocab)
type(idx2char) 

numpy.ndarray

In [153]:
for char, _ in zip( char2idx, range(len(vocab)) ):
    print('   {:4s}: {:3d}, '.format( repr(char), char2idx[char] ))
type(idx2char) 

   '\n':   0, 
   ' ' :   1, 
   '!' :   2, 
   '"' :   3, 
   '#' :   4, 
   '%' :   5, 
   "'" :   6, 
   '(' :   7, 
   ')' :   8, 
   '*' :   9, 
   '+' :  10, 
   ',' :  11, 
   '-' :  12, 
   '.' :  13, 
   '/' :  14, 
   '0' :  15, 
   '1' :  16, 
   '2' :  17, 
   '3' :  18, 
   '4' :  19, 
   '5' :  20, 
   '6' :  21, 
   '7' :  22, 
   '8' :  23, 
   '9' :  24, 
   ':' :  25, 
   ';' :  26, 
   '<' :  27, 
   '=' :  28, 
   '>' :  29, 
   '?' :  30, 
   '@' :  31, 
   'A' :  32, 
   'B' :  33, 
   'C' :  34, 
   'D' :  35, 
   'E' :  36, 
   'F' :  37, 
   'G' :  38, 
   'H' :  39, 
   'I' :  40, 
   'J' :  41, 
   'K' :  42, 
   'L' :  43, 
   'M' :  44, 
   'N' :  45, 
   'O' :  46, 
   'P' :  47, 
   'Q' :  48, 
   'R' :  49, 
   'S' :  50, 
   'T' :  51, 
   'U' :  52, 
   'V' :  53, 
   'W' :  54, 
   'X' :  55, 
   'Y' :  56, 
   '[' :  57, 
   ']' :  58, 
   '_' :  59, 
   'a' :  60, 
   'b' :  61, 
   'c' :  62, 
   'd' :  63, 
   'e' :  64, 
   'f' :  65, 
   'g' :  

numpy.ndarray

In [111]:
text_as_int = np.array( [char2idx[c] for c in text ])
text_as_int

array([47, 77, 74, ...,  1,  0,  0])

In [112]:
print('Texto   {}, '.format( repr(text[:50]) ))
print('{}, '.format( repr(text_as_int[:50]) ))

Texto   'Prologo\nEn 1953, Isaac Asimov publico Segunda Fund', 
array([47, 77, 74, 71, 74, 66, 74,  0, 36, 73,  1, 16, 24, 20, 18, 11,  1,
       40, 78, 60, 60, 62,  1, 32, 78, 68, 72, 74, 81,  1, 75, 80, 61, 71,
       68, 62, 74,  1, 50, 64, 66, 80, 73, 63, 60,  1, 37, 80, 73, 63]), 


In [113]:
char_dataset = tf.data.Dataset.from_tensor_slices( text_as_int )
char_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>

In [114]:
seq_length = 100
sequences = char_dataset.batch( seq_length+1, drop_remainder=True )
sequences

<_BatchDataset element_spec=TensorSpec(shape=(101,), dtype=tf.int64, name=None)>

In [115]:
for item in sequences.take(10):
    print(repr(''.join(idx2char[item.numpy()])))

'Prologo\nEn 1953, Isaac Asimov publico Segunda Fundacion, el tercer libro de la saga de la Fundacion ('
'o el decimotercero segun otras fuentes, este es un tema de debate). En Segunda Fundacion aparece por '
'primera vez Arkady Darell, uno de los principales personajes de la parte final de la saga. En su prim'
'era escena, Arkady, que tiene 14 anos, esta haciendo sus tareas escolares. En concreto, una redaccion'
' que lleva por titulo ?El Futuro del Plan Sheldon?. Para hacer la redaccion, Arkady esta utilizando u'
'n ?transcriptor?,un dispositivo que convierte su voz en palabras escritas. Este tipo de dispositivo, '
'que para Isaac Asimov era ciencia ficcion en 1953, lo tenemos al alcance de la mano en la mayoria de '
'nuestros smartphones, y el Deep Learning es uno de los responsables de que ya tengamos este tipo de a'
'plicaciones, siendo la tecnologia otro de ellos.En la actualidad disponemos de GPUs (Graphics Process'
'or Units), que solo cuestan alrededor de 100 euros, que estari

In [116]:
def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

In [117]:
dataset = sequences.map(split_input_target)

In [118]:
for input_example, target_example in dataset.take(1):
    print('Input data', repr( ''.join( idx2char[input_example.numpy()] ) ) )
    print('Target data', repr( ''.join( idx2char[target_example.numpy()] ) ) )

Input data 'Prologo\nEn 1953, Isaac Asimov publico Segunda Fundacion, el tercer libro de la saga de la Fundacion '
Target data 'rologo\nEn 1953, Isaac Asimov publico Segunda Fundacion, el tercer libro de la saga de la Fundacion ('


In [119]:
dataset

<_MapDataset element_spec=(TensorSpec(shape=(100,), dtype=tf.int64, name=None), TensorSpec(shape=(100,), dtype=tf.int64, name=None))>

In [120]:
BATCH_SIZE = 64
BUFFER_SIZE = 10000
dataset = dataset.shuffle( BATCH_SIZE ).batch( BATCH_SIZE, drop_remainder=True )
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(64, 100), dtype=tf.int64, name=None), TensorSpec(shape=(64, 100), dtype=tf.int64, name=None))>

In [121]:
def build_model(vocab_size, embedding_dim, rnn_units, batch_size, seq_length):

    inputs = Input(batch_size=batch_size, shape=(seq_length,), dtype='int32')

    x = Embedding(input_dim=vocab_size, output_dim=embedding_dim)(inputs)

    x = LSTM(rnn_units,
             return_sequences=True,
             stateful=True,
             recurrent_initializer='glorot_uniform')(x)

    outputs = Dense(vocab_size)(x)

    model = Model(inputs=inputs, outputs=outputs)

    return model

In [26]:
vocab_size = len(vocab) 
embedding_dim = 256
rnn_units = 1024

In [27]:
model = build_model( vocab_size, embedding_dim, rnn_units, BATCH_SIZE, None )

In [28]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (64, None)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding (Embedding)           │ (64, None, 256)        │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (64, None, 1024)       │     5,246,976 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (64, None, 91)         │        93,275 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,363,547 (20.46 MB)

 Trainable params: 5,363,547 (20.46 MB)

 Non-trainable params: 0 (0.00 B)

In [29]:
vocab_size

91

In [30]:
for input_example_batch, target_example_batch in dataset.take(1):
    print('Input', input_example_batch.shape, '# Batch size, sequence length')
    print('Input', target_example_batch.shape, '# Batch size, sequence length')

Input (64, 100) # Batch size, sequence length
Input (64, 100) # Batch size, sequence length


In [31]:
for input_example_batch, target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)
    print('Prediction', example_batch_predictions.shape, '# Batch size, sequence length, vocab size')


Prediction (64, 100, 91) # Batch size, sequence length, vocab size


In [32]:
sampled_indices = tf.random.categorical( example_batch_predictions[0], num_samples=1 )

In [33]:
sampled_indices_characters = tf.squeeze( sampled_indices, axis=-1 ).numpy()
sampled_indices_characters

array([87, 16, 20, 76, 57, 14, 87, 79, 27, 29, 89, 40, 80, 50,  3, 47, 38,
       89, 37, 32, 19, 78, 35, 57,  1, 61, 69, 61, 47, 11, 31, 86,  2, 72,
       42,  3, 11, 31, 61,  8, 18, 71, 80,  0, 12, 61, 12, 57, 32, 52, 59,
       64, 88, 81, 39,  4, 50, 19, 12,  8, 38, 11, 87, 33, 55,  0, 59, 28,
       26, 86, 78, 55, 42, 38, 61, 90, 76, 26, 63, 21, 40,  5, 63,  3, 33,
       83, 31, 86, 32, 14,  1, 51, 27, 88, 54, 17,  2, 32, 29, 34])

In [44]:
def loss(labels, logits):
    return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits=True)

In [45]:
model.compile( optimizer='adam', loss=loss )

In [46]:
checkpoint_dir = "C:/Users/jesus/Desktop/curso IA/checkpoints/"
checkpoint_prefix = checkpoint_dir + "ckpt_{epoch}.weights.h5"
checkpoint_prefix

'C:/Users/jesus/Desktop/curso IA/checkpointsckpt_{epoch}.weights.h5'

In [47]:
checkpoint_callback = tf.keras.callbacks.ModelCheckpoint( filepath=checkpoint_prefix, save_weights_only=True )

In [48]:
EPOCHS = 50
history = model.fit( dataset, epochs=EPOCHS, callbacks=[checkpoint_callback] )

Epoch 1/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 25s 786ms/step - loss: 3.5097
Epoch 2/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 24s 787ms/step - loss: 2.7306
Epoch 3/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 24s 790ms/step - loss: 2.5695
Epoch 4/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 24s 783ms/step - loss: 2.3898
Epoch 5/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 25s 792ms/step - loss: 2.2527
Epoch 6/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 25s 795ms/step - loss: 2.1470
Epoch 7/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 25s 798ms/step - loss: 2.0438
Epoch 8/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 24s 788ms/step - loss: 1.9379
Epoch 9/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 24s 785ms/step - loss: 1.8379
Epoch 10/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 25s 798ms/step - loss: 1.7418
Epoch 11/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 24s 779ms/step - loss: 1.6515
Epoch 12/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 24s 789ms/step - loss: 1.5680
Epoch 13/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 25s 792ms/step - loss: 1.4933
Epoch 14/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 25s 799ms/step - loss: 1.4280
Epoch 15/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 25s 

In [81]:
checkpoint_dir = "C:/Users/jesus/Desktop/curso IA/checkpoints/checkpointsckpt_50.weights.h5"
checkpoint_dir

'C:/Users/jesus/Desktop/curso IA/checkpoints/checkpointsckpt_50.weights.h5'

In [157]:
model = build_model( vocab_size, embedding_dim, rnn_units, 1, None )
model.load_weights( checkpoint_dir )
model.build( tf.TensorShape( [ 1, None ] ) )

In [160]:
def generate_text(model, start_string):

    num_generate = 500
    input_eval = [ char2idx[s] for s in  start_string]

    input_eval = tf.expand_dims( input_eval, 0 )
    text_generated = []

    temperature = 0.5

    for layer in model.layers:
       if isinstance(layer, LSTM) and layer.stateful:
            layer.reset_states()

    #model.reset_state()

    #model.summary()

    for i in range(num_generate):
        predictions = model(input_eval)

        predictions = tf.squeeze(predictions, 0)
        predictions = predictions / temperature

        predicted_id = tf.random.categorical( predictions, num_samples=1 )[-1,0].numpy()

        input_eval = tf.expand_dims( [ predicted_id ], 0 )



        text_generated.append( idx2char[predicted_id] )

    return ( start_string + ''.join( text_generated ) )
        

In [161]:


print( generate_text(model, u"Domingo ") )


Domingo tando, con el gradiente.  En gitale es que es igualmente se ajustara tambien cambiar el pooling tenemos 12?12 neuronas que corresponde a la capa convolucional y convolucion y pooling. En nuestro caso, tendremos 32 filtros, de cada capa oculta de aprendizaje con el metodo fit() y no sera es una capa convolucional y crean una version condensada de la informacion en la segunda capa de convolucion y pooling. En nuestro caso, usaremos un modelo simplificar el numero de pasos en que el modelo y contra


In [162]:
print( generate_text(model, start_string=u"Activation ") )

Activation y despues de puntos de aprendizaje de una red neuronal. En concreto esta arquitectura es referenciada en las capas ocultas de datos de tamano 2x2 que aparecen al dividir el espacio de neuronas se pueden aprender patrones hocales en un numero de filtros que usamos para retocar imagenes como veremos en la segunda parte del libro entraremos en detalle se dispone del minimo como la aparacion de convolucion, conseguiamos de la siguiente figura: 





En este caso, el numero de caracteristicas que que


In [163]:
print( generate_text(model, start_string=u"Redes ") )

Redes conteneder disenados para facilitar la capa de pooling. Visualmente, podemos resumir de computadores de cada capa oculta. Y asi, sucesivamente ha introducida en el capitulo anterior para el modelo. 




2.1 Redes neuronales densas; despues de ejecutar estas instrucciones indicadas quedando una red neuronal convolucional con las capas de convolucionales con el max-pooling como el numero de epochs hasta que otra secuencia entre el detalle de cada uno de los parametros de la capa convolucional y un


In [164]:
print( generate_text(model, start_string=u"a ") )

a continuacion. En la capa de convolucion con unas capas de pooling contendra tantos contienen el valor mas alto de datos de talor mas sobre esta herramienta vomontrar con mas detalle de cada uno de los parametros de la diagonal de entrada de 28?28 pixeles se muestra como ar ustemos una ventana de 2?2. 

Arquitectura de modelo mas alla del capitulo tiene esta escritorno en una red neuronal convolucional en Keras. Como hemos comentado, hay varios valores cada vez mas complejos y visualmente esta ca
