In [2]:
import tensorflow as tf
from random import randint 
import random
import numpy as np

In [3]:
print("GPU avalable:  ",  tf.config.list_physical_devices('GPU'))

GPU avalable:   []


In [4]:
print(tf.__version__)

2.19.0


In [5]:
print(tf.keras.__version__)

3.9.2


In [6]:
randomint = random.randint(1, 100)

In [7]:
print(randomint)

39


In [8]:
x = np.array(8)

In [9]:
x

array(8)

In [10]:
x.ndim

0

In [11]:
x.shape

()

In [12]:
x.size

1

In [13]:
x.dtype

dtype('int64')

In [14]:
x = np.array([2.3, 4.2, 3.3, 1.8])

In [15]:
x

array([2.3, 4.2, 3.3, 1.8])

In [16]:
x.ndim

1

In [17]:
x.shape

(4,)

In [18]:
x.size

4

In [19]:
x.dtype

dtype('float64')

In [20]:
x = np.array([[1,2,3], [4,5,6], [5,6,7] ])

In [21]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [22]:
x.ndim

2

In [23]:
x.shape

(3, 3)

In [24]:
x.size

9

In [25]:
x = np.array( [[[ 1,2], [3,4]],  [[5,6], [7,8] ]]  )

In [26]:
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [27]:
x.ndim

3

In [28]:
x.shape

(2, 2, 2)

In [29]:
x.size

8

In [30]:
np.zeros(( 3,3 ))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones(( 3,3 ))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.eye(( 3 ))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.random.random(( 3,3 ))

array([[0.88115549, 0.14889173, 0.37366764],
       [0.75901311, 0.12376665, 0.09773361],
       [0.17926927, 0.28775389, 0.1656385 ]])

In [34]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12] ])

In [35]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
x[:,1]

array([ 2,  6, 10])

In [37]:
x[:,0]

array([1, 5, 9])

In [38]:
x[1,:]

array([5, 6, 7, 8])

In [39]:
x[0,:]

array([1, 2, 3, 4])

In [40]:
a = np.array( [ [ 1,2,3 ], [4,5,6] ], dtype=np.int32 )

In [41]:
b = np.array( [ [ 1,2], [3,4], [5,6] ], dtype=np.int32 )

In [42]:
c = a.dot(b)

In [43]:
c

array([[22, 28],
       [49, 64]], dtype=int32)

In [44]:
x = np.array( [ [ 1,2,3,4,5,6] ] )

In [45]:
x

array([[1, 2, 3, 4, 5, 6]])

In [46]:
x.shape

(1, 6)

In [47]:
y = np.reshape(x, (2,3))

In [48]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
z = np.reshape(x, (2,-1))

In [50]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
x = np.array( [ [ 1,2,3], [4,5,6] ] )

In [52]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
y = np.expand_dims(x, 1)

In [54]:
y

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [55]:
x = np.array( [[[ 1,2,3]], [[4,5,6]]] )

In [56]:
x

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [57]:
y = np.squeeze(x, 1)

In [58]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
x = np.array([1, 2, 3, 4])

In [60]:
x

array([1, 2, 3, 4])

In [61]:
np.argmax(x)

np.int64(3)

In [62]:
np.max(x)

np.int64(4)